import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoField;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


private Object tanggalPertama;
    private Object tanggalKedua;
    private String selisihHari;
/**
 *
 * @author ASUS
 */
public class AplikasiPenghitungHari extends javax.swing.JFrame {
    
    //Variabel untuk simpan tanggal klik pertama dan kedua
    private Date tanggalPertama = null;
    private Date tanggalKedua = null;

    private String selisihHari;
    

    /**
     * Creates new form AplikasiPenghitungHari
     */
    public AplikasiPenghitungHari() {
        initComponents();
        isiComboBulan();
        setTitle("Aplikasi Penghitung Hari");
        setLocaltionRelativeTo(null);
        setResizable(false);
        pack();
        
        //Event klik tanggal di Jcalender
        jCalendar1.getDayChooser().addPropertyChangeListener("day", evt -> {
            handleTanggalDipilih();
        });
        
    }
    
    // Isi combo box bulan
    private void isiComboBulan() {
        jComboBox1.removeAllItems();
        String[] bulan = {"Januari", "Februari", "Maret", "April", "Mei", "Juni",
                          "Juli", "Agustus", "September", "Oktober", "November", "Desember"};
        for (String b : bulan) {
            jComboBox1.addItem(b);
        }
        jComboBox1.setSelectedIndex(0);
        jSpennerTahun.setValue(2025);
    }
    
    //cek tahun kabisat
    private boolean isKabisat(int tahun) {
        return (tahun % 4 == 0 && tahun % 100 != 0) || (tahun % 400 == 0);
        
    }

    //format hari ke bahasa indonesia 
    private String formatHari(String hari) {
        return switch (hari.toUpperCase()) {
            case "MONDAY" -> "Senin";
            case "TUESDAY" -> "Selasa";
            case "WEDNESDAY" -> "Rabu";
            case "THURSDAY" -> "Kamis";
            case "FRIDAY" -> "jumat";
            case "SATURDAY" -> "Sabtu";
            case "SUNDAY" -> "Minggu";
            default -> hari;
        };
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AplikasiPerhitunganHari = new javax.swing.JLabel();
        InputBulan = new javax.swing.JLabel();
        InputTahun = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpennerTahun = new javax.swing.JSpinner();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        SilahkanPilihTanggal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        HasilPerhitungan = new javax.swing.JLabel();
        BulanTahun = new javax.swing.JTextField();
        TahunKeluar = new javax.swing.JTextField();
        HariPertama = new javax.swing.JTextField();
        HariTerakhir = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        DariTahun = new javax.swing.JTextField();
        SampaiTahun = new javax.swing.JTextField();
        TotalSelisih = new javax.swing.JTextField();
        btnHitungSelisih = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        AplikasiPerhitunganHari.setBackground(new java.awt.Color(255, 204, 204));
        AplikasiPerhitunganHari.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AplikasiPerhitunganHari.setForeground(new java.awt.Color(255, 255, 255));
        AplikasiPerhitunganHari.setText("APLIKASI PENGHITUNG HARI ");

        InputBulan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputBulan.setForeground(new java.awt.Color(255, 255, 255));
        InputBulan.setText("Input Bulan ");

        InputTahun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputTahun.setForeground(new java.awt.Color(255, 255, 255));
        InputTahun.setText("Input Tahun");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Perhitungan Selisih ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        btnHitung.setBackground(new java.awt.Color(255, 204, 204));
        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(102, 102, 102));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        SilahkanPilihTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SilahkanPilihTanggal.setForeground(new java.awt.Color(255, 255, 255));
        SilahkanPilihTanggal.setText("Silahkan Pilih Tanggal : ");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        HasilPerhitungan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HasilPerhitungan.setForeground(new java.awt.Color(255, 255, 255));
        HasilPerhitungan.setText("Hasil Perhitungan");

        TahunKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunKeluarActionPerformed(evt);
            }
        });

        HariPertama.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        HariPertama.setText("Hari Pertama :");
        HariPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HariPertamaActionPerformed(evt);
            }
        });

        HariTerakhir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        HariTerakhir.setText("Hari Terakhir:");
        HariTerakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HariTerakhirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HasilPerhitungan)
                .addGap(119, 119, 119))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HariPertama)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BulanTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TahunKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(HariTerakhir))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HasilPerhitungan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TahunKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BulanTahun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HariPertama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HariTerakhir, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        DariTahun.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        DariTahun.setText("Dari :");

        SampaiTahun.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        SampaiTahun.setText("Sampai :");

        TotalSelisih.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        TotalSelisih.setText("Selisih :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalSelisih, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SampaiTahun, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(DariTahun)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(DariTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SampaiTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnHitungSelisih.setBackground(new java.awt.Color(255, 204, 204));
        btnHitungSelisih.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHitungSelisih.setText("Hitung Selisih");
        btnHitungSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungSelisihActionPerformed(evt);
            }
        });

        btnReset2.setBackground(new java.awt.Color(102, 102, 102));
        btnReset2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset2.setText("Reset");
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(102, 102, 102));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputTahun)
                                    .addComponent(InputBulan))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, 197, Short.MAX_VALUE)
                                    .addComponent(jSpennerTahun)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset)))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(AplikasiPerhitunganHari)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHitungSelisih)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SilahkanPilihTanggal)
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(AplikasiPerhitunganHari)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputBulan)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(InputTahun))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSpennerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SilahkanPilihTanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHitungSelisih)
                            .addComponent(btnReset2)
                            .addComponent(btnKeluar))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        jComboBox1.setSelectedIndex(0);
        jSpennerTahun.setValue(2025);
        BulanTahun.setText("");
        TahunKeluar.setText("");
        HariPertama.setText("");
        HariTerakhir.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            int bulan = jComboBox1.getSelectedIndex() + 1;
            int tahun = (int) jSpennerTahun.getValue();

            LocalDate tanggal = LocalDate.of(tahun, bulan, 1);
            int jumlahHari = tanggal.lengthOfMonth();
            String haripertama = tanggal.getDayOfWeek().toString();
            String hariterakhir = tanggal.withDayOfMonth(jumlahHari).getDayOfWeek().toString();

            //tampilan bulan dan tahun
            BulanTahun.setText("Bulan: " + jComboBox1.getSelectedItem() + " " + tahun);

            //tampilkan tahun + status kabisat
            TahunKeluar.setText("Tahun: " + tahun + (isKabisat(tahun) ? " (Kabisat) " : " (Bukan Kabisat)"));

            //hari pertama dan terakhir 
            HariPertama.setText("Hari Pertama: " + formatHari(HariPertama));
            HariTerakhir.setText("Hari Terakhir: " + formatHari(HariTerakhir));

            JOptionPane.showMessageDialog(this,
                    "Jumlah hari pada " + jComboBox1.getSelectedItem() + " " + tahun
                    + "adalah " + jumlahHari + "hari.",
                    "Hasil Perhitungan", JOptionPane.INFORMATION_MESSAGE);

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Input!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungActionPerformed
        //klik 2 kali tanggal hitung selisih 

        private void handletanggalDipilih() {
            Date tanggalDipilih = jCalendar1.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("d MMMM yyyy", new Locale("id", "ID"));

            if (tanggalPertama == null) {
                // klik pertama
                tanggalPertama = tanggalDipilih;
                DariTahun.setText("Dari: " + sdf.format(tanggalPertama));
                SampaiTahun.setText("");
                TotalSelisih.setText("");
            } else if (tanggalKedua == null) {
                // klik kedua
                tanggalKedua = tanggalDipilih;
                SampaiTahun.setText("Sampai: " + sdf.format(tanggalKedua));

                LocalDate dari = tanggalPertama.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                LocalDate sampai = tanggalKedua.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

                long selisihHari = Math.abs(ChronoUnit.DAYS.between(dari, sampai));
                TotalSelisih.setText("Selisih: " + selisihHari + " hari");

                JOptionPane.showMessageDialog(this,
                        "Selisih antara " + sdf.format(tanggalPertama) + " dan "
                        + sdf.format(tanggalKedua) + " adalah " + selisihHari + " hari.",
                        "Hasil Selisih", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // klik ketiga → reset
                tanggalPertama = tanggalDipilih;
                tanggalKedua = null;
                DariTahun.setText("Dari: " + sdf.format(tanggalPertama));
                SampaiTahun.setText("");
                TotalSelisih.setText("");
            }
        }

        private String formatHari(JTextField HariPertama) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
    private void TahunKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunKeluarActionPerformed

    private void HariTerakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HariTerakhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HariTerakhirActionPerformed

    private void HariPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HariPertamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HariPertamaActionPerformed

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        DariTahun.setText("");
        SampaiTahun.setText("");
        TotalSelisih.setText("");
        tanggalPertama = null;
        tanggalKedua = null;
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void btnHitungSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungSelisihActionPerformed
        try {
            // Ambil dua tanggal dari dua kalender
            Date tanggalDari = jCalendar1.getDate();
            Date tanggalSampai = jCalendar1.getDate();

            if (tanggalDari == null || tanggalSampai == null) {
                JOptionPane.showMessageDialog(null, "Silakan pilih kedua tanggal terlebih dahulu!");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("d MMMM yyyy", new Locale("id", "ID"));
            LocalDate dari = tanggalDari.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            LocalDate sampai = tanggalSampai.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

            DariTahun.setText("Dari: " + sdf.format(tanggalDari));
            SampaiTahun.setText("Sampai: " + sdf.format(tanggalSampai));
            TotalSelisih.setText("Selisih: " + selisihHari + "hari");

            JOptionPane.showMessageDialog(null,
                    "Selisih antara " + sdf.format(tanggalDari) + " dan "
                    + sdf.format(tanggalSampai) + "adalah" + selisihHari + " hari. ",
                    "Hasil Selisih", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan dalam menghitung selisih!");
        }

    }//GEN-LAST:event_btnHitungSelisihActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // (boleh dikosongkan atau dibiarkan oleh NetBeans)

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new AplikasiPenghitungHari().setVisible(true);

        }
    });
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AplikasiPerhitunganHari;
    private javax.swing.JTextField BulanTahun;
    private javax.swing.JTextField DariTahun;
    private javax.swing.JTextField HariPertama;
    private javax.swing.JTextField HariTerakhir;
    private javax.swing.JLabel HasilPerhitungan;
    private javax.swing.JLabel InputBulan;
    private javax.swing.JLabel InputTahun;
    private javax.swing.JTextField SampaiTahun;
    private javax.swing.JLabel SilahkanPilihTanggal;
    private javax.swing.JTextField TahunKeluar;
    private javax.swing.JTextField TotalSelisih;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHitungSelisih;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jSpennerTahun;
    // End of variables declaration//GEN-END:variables


    private boolean isKabisat(int tahun) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String formatHari(JTextField HariPertama) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void isiComboBulan() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setLocaltionRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void handleTanggalDipilih() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private static class jCalender1 {

        public jCalender1() {
        }
    }
